global:
  annotations:
    foo.bar.com: "foobar"
    bar.foo.com: "barfoo"
    #env:
    #  FOO: BAR
  labels:
    team: ops
    severity: noncritical
    global: labels

deployments:
  nginx:
    service:
      type: ClusterIP
      ports:
        http:
          port: 80
          protocol: TCP
          targetPort: 80
    annotations:
      foo.bar.net: "foobar"
      foo.bar.com: "override"
    labels:
      deployment: labels
    replicas: 3
    containers:
      nginx:
        image: nginx
        env:
          PG_USERNAME: todo
          PG_DATABASE: todo
          PG_HOST: postgres-primary
          PG_PORT: "5432"
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
           memory: 1Gi
           cpu: "0.1"
          limits:
            memory: 2Gi

files:
  foo.conf: json://path/to/file
  conf: file://

secrets:
  TODO_PASSWORD: todo_password
