global:
  annotations:
    foo.bar.com: "foobar"
    bar.foo.com: "barfoo"
    #env:
    #  FOO: BAR
  labels:
    team: ops
    severity: noncritical
    global: labels

deployments:
  near-indexer:
    service:
      type: LoadBalancer
      ports:
        http:
          port: 80
          protocol: TCP
          targetPort: 8080
    annotations:
      foo.bar.net: "foobar"
      foo.bar.com: "override"
    labels:
      deployment: labels
    replicas: 3
    containers:
      todo-app:
        image: lhopki01/todo-app:0.1.0
        env:
          PG_USERNAME: todo
          PG_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: todo-app
                key: TODO_PASSWORD
          PG_DATABASE: todo
          PG_HOST: postgres-primary
          PG_PORT: "5432"
        readinessProbe:
          httpGet:
            path: /healthcheck/readiness
            port: 8080
        livenessProbe:
          disabled: true
          #httpGet:
          #  path: /healthcheck/liveness
          #  port: 8080
        resources:
          requests:
           memory: 1Gi
           cpu: 200Mi
          limits:
            memory: 2Gi
        securityContext:
          runAsNonRoot: false

files:
  foo.conf: json://path/to/file
  conf: file://

secrets:
  TODO_PASSWORD: todo_password
